/**
 * This file is automatically generated. Do not edit manually.
 */
import type { FirebaseOptions } from 'firebase/app';

// Your web app's Firebase configuration
// For Firebase JS SDK v7.20.0 and later, measurementId is optional
const firebaseConfig: FirebaseOptions = {
  apiKey: "AIzaSyAS54ArJKogYpzoYveqaaNa-fC5lQVbGhI",
  authDomain: "malhotra-publishing-house.firebaseapp.com",
  projectId: "malhotra-publishing-house",
  storageBucket: "malhotra-publishing-house.appspot.com",
  messagingSenderId: "10331464575",
  appId: "1:10331464575:web:83d43636f0ccbca01f704a",
  measurementId: "G-3TZZZ4ZTXX"
};


export function getFirebaseConfig(): FirebaseOptions {
  if (!firebaseConfig || !firebaseConfig.apiKey) {
    throw new Error(
      'No Firebase configuration object provided.' +
        'Add your web app\'s configuration object to firebase-config.ts'
    );
  }
  return firebaseConfig;
}
